"""ALP codec tests — round-trips, edge cases, and Java byte-equality."""

from __future__ import annotations

import struct

import numpy as np
import pytest

from alp import decode, encode
from alp._bit_packing import compute_bit_width, find_frame, pack, unpack
from alp._encoder import decode_value, encode_value, find_best_exponents


def _bits_equal(actual: np.ndarray, expected: list[float]) -> None:
    assert len(actual) == len(expected)
    for i, (a, e) in enumerate(zip(actual, expected, strict=False)):
        assert struct.pack("<d", float(a)) == struct.pack("<d", float(e)), (
            f"row {i}: {a!r} != {e!r}"
        )


# --- High-level encode/decode round-trips -----------------------------------

def test_empty_roundtrip() -> None:
    blob = encode([])
    # 4-byte count header only
    assert blob == b"\x00\x00\x00\x00"
    assert decode(blob).size == 0


def test_prices_2dp_roundtrip() -> None:
    values = [65007.28, 65007.31, 65007.30, 65007.32, 65007.32]
    decoded = decode(encode(values))
    np.testing.assert_array_equal(decoded, values)


def test_integers_roundtrip() -> None:
    values = [1.0, 2.0, 3.0, 4.0, 5.0]
    decoded = decode(encode(values))
    np.testing.assert_array_equal(decoded, values)


def test_identical_values_roundtrip() -> None:
    values = [3.14, 3.14, 3.14, 3.14]
    decoded = decode(encode(values))
    np.testing.assert_array_equal(decoded, values)


def test_mixed_values_roundtrip() -> None:
    values = [-12.5, -12.6, 0.0, 100.0, 1.234]
    decoded = decode(encode(values))
    np.testing.assert_array_equal(decoded, values)


def test_decimal_fractions_roundtrip() -> None:
    """0.1, 0.2, ... aren't representable in binary; ALP must mark them as
    exceptions at e=0, but for any e≥1 the values round-trip."""
    values = [0.1, 0.2, 0.3, 0.4, 0.5]
    decoded = decode(encode(values))
    np.testing.assert_array_equal(decoded, values)


def test_two_vectors_roundtrip() -> None:
    """Boundary case: more than VECTOR_SIZE rows so encode produces 2 chunks."""
    n = 1500
    rng = np.random.default_rng(42)
    values = (rng.integers(0, 100_000, size=n).astype(np.float64) / 100.0).tolist()
    decoded = decode(encode(values))
    np.testing.assert_array_equal(decoded, values)


# --- Per-value encoder / decoder primitives ---------------------------------

def test_encode_decode_value_roundtrip_for_2dp() -> None:
    for v in [65007.28, 0.5, 100.0, -42.5]:
        e, f = find_best_exponents(np.asarray([v]), 1, sample_size=4)
        enc = encode_value(v, e, f)
        dec = decode_value(enc, e, f)
        assert struct.pack("<d", dec) == struct.pack("<d", v)


# --- Bit-packing primitive --------------------------------------------------

def test_bit_packing_roundtrip_random_widths() -> None:
    rng = np.random.default_rng(7)
    for bit_width in (1, 5, 8, 13, 24, 33, 60, 64):
        if bit_width >= 64:
            high = 1 << 32
        else:
            high = (1 << bit_width) - 1
        n = 100
        deltas = rng.integers(0, high + 1, size=n, dtype=np.int64)
        frame = -42
        values = deltas + frame
        packed = pack(values, n, frame, bit_width)
        unpacked = unpack(packed, n, frame, bit_width)
        np.testing.assert_array_equal(unpacked, values)


def test_bit_packing_zero_width() -> None:
    values = np.array([7, 7, 7, 7], dtype=np.int64)
    frame = find_frame(values, len(values))
    bit_width = compute_bit_width(values, len(values), frame)
    assert bit_width == 0
    packed = pack(values, len(values), frame, bit_width)
    assert packed == b""
    unpacked = unpack(packed, len(values), frame, bit_width)
    np.testing.assert_array_equal(unpacked, values)


# --- Cross-implementation: bytes generated by alp-java AlpCompressor --------

JAVA_FIXTURES = {
    "ints": (
        [1.0, 2.0, 3.0, 4.0, 5.0],
        "000000050000030000000000000001000000028846",
    ),
    "prices_2dp": (
        [65007.28, 65007.31, 65007.30, 65007.32, 65007.32],
        "000000050200030000000000633178000000029848",
    ),
    "identical": (
        [3.14, 3.14, 3.14, 3.14],
        "00000004020000000000000000013a00000000",
    ),
    "decimal_fractions": (
        [0.1, 0.2, 0.3, 0.4, 0.5],
        "000000050100030000000000000001000000028846",
    ),
    "mixed": (
        [-12.5, -12.6, 0.0, 100.0, 1.234],
        "00000005030011ffffffffffffcec80000000b64000000e0c4c0bead6003",
    ),
}


def test_python_encode_matches_java_byte_for_byte() -> None:
    for label, (values, expected_hex) in JAVA_FIXTURES.items():
        produced = encode(values).hex()
        assert produced == expected_hex, (
            f"{label}: python produced {produced}, java produced {expected_hex}"
        )


def test_python_decode_of_java_bytes_matches_input() -> None:
    for label, (values, hex_blob) in JAVA_FIXTURES.items():
        decoded = decode(bytes.fromhex(hex_blob))
        _bits_equal(decoded, values)


# --- Truncation handling -----------------------------------------------------

def test_decode_rejects_truncated_count_header() -> None:
    with pytest.raises(ValueError, match="missing 4-byte count"):
        decode(b"\x00\x00")


def test_decode_rejects_truncated_vector_header() -> None:
    blob = b"\x00\x00\x00\x05\x00\x00\x00"  # claims 5 values but only 3 header bytes
    with pytest.raises(ValueError, match="truncated ALP vector header"):
        decode(blob)
